# Generated by Django 2.2 on 2020-01-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
