# Generated by Django 2.2 on 2020-01-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokbox', '0004_auto_20200108_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
