# Generated by Django 2.2 on 2020-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokbox', '0005_auto_20200108_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(null=True),
        ),
    ]
