# Generated by Django 2.2 on 2020-01-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokbox', '0006_auto_20200109_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
