# Generated by Django 2.2 on 2020-01-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokbox', '0007_auto_20200110_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_slides',
            field=models.FileField(null=True, upload_to='media', verbose_name='Slides'),
        ),
    ]
